= Packaged oasp4js AngularJS modules

[NOTE]
===============================
*OASP has been superseded by devonfw*, the Open Source Standard Software Development Platform for state of the art Cloud Native Micro Service and Multi Platform Rich Web Apps, supported by Capgemini.

See http://devonfw.com and on Github http://github.com/devonfw

Individual products within OASP have been renamed to a corresponding one in devonfw. 

For example:

- OAPS4j -> devon4j
- OASP4js -> devon4ng
- OASP4NET -> devon4NET

devonfw® is an exclusive and registered (European Trademark) product of Capgemini. Capgemini reserves all intellectual and industrial property rights over devonfw but publishes it under the Apache License, Version 2 – like OASP-  which makes devonfw 100% Open Source.
See: https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)
===============================

This repository is for distribution on `bower`. The source for this module can be found in
https://github.com/oasp/oasp4js[this repository].

== Install

=== Instructions for installing ng-modules for OASP4JS Application Template

If you have already set up the https://github.com/oasp/generator-oasp[OASP4JS Application Template] and you want to use OASP4JS ng-modules you have to perform steps listed below.

Install package using bower.

....
bower install oasp --save
.... 

The `save` parameter will add the package to the dependencies in the `bower.json` file. The OASP4JS Application Template uses https://github.com/taptapship/wiredep[wiredep] which will automatically attach all needed scripts to the `index.html` file (including `oasp.min.js` needed here).

=== Instructions for other applications

If you are developing your own application without the OASP4JS Application Template and you are not using plugins which will attach scripts automatically to your main html, please perform the following steps.

Install the package using `bower`:

....
bower install oasp
....
Then add a `<script>` to your `index.html`:

[source,html]
....
<script src="/bower_components/oasp/oasp.min.js"></script>
....

== Documentation

Documentation of the ng-modules is available on the https://github.com/oasp/oasp4js/wiki/oasp4js-ng-modules[Wiki].
